[tool.poetry]
name = "model-recycling-stats"
version = "0.1.0"
description = ""
authors = ["Harsh Patel <pharsh58@gmail.com>"]
readme = "README.md"
packages = [{include = "model_recycling_stats"}]

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
pydantic = "^1.10.8"
PyDriller = "^2.4.1"
pandas = "^2.0.2"
cliffs-delta = "^1.0.0"
scipy = "^1.10.1"
seaborn = "^0.12.2"
Jinja2 = "^3.1.2"
tabulate = "^0.9.0"


[tool.poetry.group.dev.dependencies]
mypy = "^1.3.0"
flake8 = "^6.0.0"
black = "^23.3.0"
ipykernel = "^6.23.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 100
target-version = ['py39']

[tool.poetry.scripts]
stat_test = "model_recycling_stats.stat_test:main"
median_improv = "model_recycling_stats.calc_median_improv:main"